### PR TITLE
Deprecate this module

### PR DESCRIPTION
**Pull request by brandones**

### CODE REVIEW

**Review by mogoodrich — CHANGES_REQUESTED** [review]
This isn't 100% correct, sorry if I wasn't clear... there's at least one other pieces of functionality in this module, the dispensing form itself, and I think a couple other things... but generally agree with depreciation... it basically has some targeted dispensing functionality we use at PIH but likely shouldn't be considered a base for someone developing their own dipensing functionality.

**Comment by brandones** [comment]
Oh whoops! Right, of course -- this is that whole dispensing app, which Ellen demoed for me. It's on humci? I could update the README to be more helpful.

Seems like this has
- the drug importer
- a special patient search page
- a special patient dashboard page
- a dispensing summary page
- extensions to link in from the refapp patient dashboard

Anything obviously missing?

**Comment by mogoodrich** [comment]
@brandones  that sounds about right...

**Comment by brandones** [comment]
Stale; closing.

**Pull request closed without merging**
